### ISSUE TITLE
想参与BaseX小组中

### ISSUE THREAD

**Issue by luckzhiwei** [BeesX/BeesAndroid#26]
## 文章描述

文章标题：想参与BaseX小组中

## 问题描述
你好，看到了你们整理的Android源代码资料，感觉很详实，对我帮组很大，不知道我是否可以也参与到这个项目中来，为BaseAndroid的源代码分析贡献一份力量

**Comment by sucese** [comment]
可以的，我的微信 allenwells。

**Comment by luckzhiwei** [comment]
好的，我明天加下
